use_frameworks!

target 'ConfigPrivatePod_Example' do
  pod 'ConfigPrivatePod', :path => '../'

  target 'ConfigPrivatePod_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
